### ISSUE TITLE
[MyAAC] Erro com Canary 1.3.0 - MyAAC v0.8.6

### ISSUE THREAD

**Issue by cssiqueira** [otsoft/myaac#198] opened 2022-06-11 07:18 UTC
I'm using the newest MyAcc and some errors are happening because the new Canary (otservbr) doesn't have some xml files which myacc uses, I would like to know if anyone managed to fix it. Below I put the errors

in creatures

Reload monsters.
All records deleted from table 'myaac_monsters' in database.
Error: Cannot load monsters.xml. File not found. More info in system/logs/error.log file.

in exp stages
Error: cannot load stages.xml!

in spells
Reload spells.
All records deleted from table myaac_spells in database.
Error: Cannot load spells.xml. File not found. More info in system/logs/error.log file.

in Library items
although the items.xml does not give an error when clicking on any option (legs, helm, weapons, etc) gives an error eg: Not Found
The requested URL /?items/weapon was not found on this server.

in the Admin Panel by clicking reload on the items page
Cannot load file c:/tibia/serve/data/weapons/weapons.xml

Sorry for the English, I'm using google translator

### Server configuration
- Operating System: windows 10
- Web Server (+ version):  XAMPP Version: 7.4.27
- PHP Version: XAMPP Version: 7.4.27
- Server name and version (for example: TFS 0.3): otservbr / canary 1.3.0 / client 12.86
- MyAAC Version: MyAAC v0.8.6

### Client configuration (Your Computer)

- Browser: 
- Operating System: windows 10

### Steps To Reproduce:

**Comment by slawkens** [comment] 2022-06-15 12:48
Hello,

This is duplicate of #189

Except one thing: Items. You probably mean this plugin: list_of_items.

You can download fixed version here: https://my-aac.org/plugins

**Closed by slawkens** 2022-06-15 12:48 UTC
Labels: duplicate

**Comment by cssiqueira** [comment] 2022-06-15 13:54
> Hello,
> 
> This is duplicate of #189
> 
> Except one thing: Items. You probably mean this plugin: list_of_items.
> 
> You can download fixed version here: https://my-aac.org/plugins

Well, thank you in advance for your help, I downloaded the 3.0 version of the plugin as you mentioned, I reloaded the items again (just to reinforce the action and for there to be no doubts I stopped and restarted in xamp, in addition to testing in an incognito window in chrome and in firefox) and even so it accuses an error when clicking on the options follows print.
![Captura de Tela (489)](https://user-images.githubusercontent.com/107297566/173843605-91e355e4-9fb7-4c05-bafc-40253f5cc135.png)
![Captura de Tela (490)](https://user-images.githubusercontent.com/107297566/173843615-a053b08f-911e-483b-84a6-011d9863fbbf.png)
![Captura de Tela (491)](https://user-images.githubusercontent.com/107297566/173843622-d4cb0836-d06c-4991-9698-c3467dcebbf2.png)
